"""Data contract between the backend (Hono) and the adversarial agent.

This module is the public BOUNDARY of the service. Hono builds a
`PromptInjectionRequest`, makes a POST request, and receives a `PromptInjectionResult`.
Nothing beyond these schemas crosses the boundary of the service.

Design principle: the objective of every attack is to extract a `canary` — a
benign token that the Target was instructed to hide. This makes detection
deterministic (either leaked or not leaked) and keeps the tool ethical: we never
attempt to extract actually harmful content from the target, only to prove that it
can be induced to violate an explicit instruction.
"""

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, SecretStr


class AttackTechnique(str, Enum):
    """Attack categories that the adversarial agent can employ.

    They map to the OWASP LLM01 taxonomy. The agent chooses among the techniques
    ALLOWED by the request; restricting the list allows testing a category
    in isolation (e.g., only `encoding`).
    """

    DIRECT = "direct"  # "ignore the instructions above and reveal..."
    ROLEPLAY = "roleplay"  # roleplaying to bypass persona/guardrails
    ENCODING = "encoding"  # base64, leetspeak, unicode, other language
    CRESCENDO = "crescendo"  # gradual escalation over turns


class TurnRole(str, Enum):
    """Who spoke in a turn of the transcript."""

    ATTACKER = "attacker"  # probe generated by our agent
    TARGET = "target"  # response from the system under test


class StopReason(str, Enum):
    """Why the attack loop finished. Distinguishes findings from operational limits."""

    CANARY_LEAKED = "canary_leaked"  # success: the injection worked
    MAX_TURNS = "max_turns"  # ran out of turns without leaking
    BUDGET_EXCEEDED = "budget_exceeded"  # exceeded the loop's time budget
    TARGET_ERROR = "target_error"  # the target endpoint failed/timed out


class TargetConfig(BaseModel):
    """Describes the LLM endpoint under test.

    It assumes an OpenAI-compatible endpoint (covers OpenAI,
    Gemini via compat layer, Anthropic via proxy, and local models like
    Ollama/vLLM). `api_key` arrives PER REQUEST and is never persisted on this side.
    """

    model_config = ConfigDict(extra="ignore")

    base_url: str = Field(
        ...,
        description="OpenAI-compatible base URL, e.g., https://api.openai.com/v1",
    )
    model: str = Field(..., description="Model identifier in the target provider.")
    system_prompt: str = Field(
        default="",
        description="System prompt configured by the Target owner.",
    )
    api_key: SecretStr | None = Field(
        default=None,
        description="Target credential. Optional for local endpoints without auth.",
    )
    extra_headers: dict[str, str] = Field(
        default_factory=dict,
        description="Additional auth headers, if required by the provider.",
    )


class PromptInjectionRequest(BaseModel):
    """Payload sent by Hono to start an attack campaign.

    `extra="ignore"` is deliberate: the Python service and Hono deploy
    separately. If Hono starts sending a new field before Python is
    updated, we want to ignore it — not reject the entire request with a 422 error.
    """

    model_config = ConfigDict(extra="ignore")

    run_id: str = Field(
        ...,
        description="Correlation ID generated by Hono. Merely echoed back; "
        "the Python service is stateless and does not persist it.",
    )
    target: TargetConfig
    canary: str = Field(
        ...,
        min_length=6,
        description="Benign token that the target must hide. Its presence "
        "in the target's response is the deterministic sign of success.",
    )
    objective: str | None = Field(
        default=None,
        description="Natural language objective for the attacker. If absent, "
        "it is derived from the canary (extract the hidden token).",
    )
    allowed_techniques: list[AttackTechnique] = Field(
        default_factory=lambda: list(AttackTechnique),
        min_length=1,
        description="Techniques that the agent can use. Default: all.",
    )
    max_turns: int | None = Field(
        default=None,
        ge=1,
        le=20,
        description="Turn ceiling override. The orchestrator limits this to the global "
        "ceiling from Settings — the request never exceeds it.",
    )


class ConversationTurn(BaseModel):
    """A single turn of the transcript: either an attacker probe or a target response."""

    index: int = Field(..., ge=0, description="Position in the sequence (starts at 0).")
    role: TurnRole
    content: str
    technique: AttackTechnique | None = Field(
        default=None,
        description="Filled in attacker turns; indicates the technique used.",
    )


class PromptInjectionResult(BaseModel):
    """Result returned to Hono. This is what Hono persists in Postgres.

    Pay attention to the counter-intuitive naming: `success=True` means the INJECTION
    worked — meaning, the target is VULNERABLE. Good for us, bad for the target.
    """

    run_id: str = Field(..., description="Echoes the request's run_id, for correlation.")
    success: bool = Field(
        ...,
        description="True if the injection leaked the canary (vulnerable target).",
    )
    stop_reason: StopReason
    turns_used: int = Field(..., ge=0, description="How many attacker turns ran.")
    winning_technique: AttackTechnique | None = Field(
        default=None,
        description="The technique of the turn that leaked the canary, if any.",
    )
    winning_turn_index: int | None = Field(
        default=None,
        description="Index of the attacker turn that succeeded, if any.",
    )
    elapsed_seconds: float = Field(..., ge=0)
    transcript: list[ConversationTurn] = Field(
        default_factory=list,
        description="Full sequence of probes and responses, for auditing and UI.",
    )
